version: "{build}"

platform: x64

clone_depth: 10

environment:
  matrix:
    - NODE_VERSION: 6.9.1

install:
  - ps: Install-Product node $env:NODE_VERSION
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run ci

deploy: off
