environment:
  nodejs_version: "6"

platform: x64

image: Visual Studio 2015

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run coffeelint -r src spec && eslint src spec
  - npm run devtool  --quit --console node_modules/mocha/bin/_mocha --colors spec/helpers/setup.js spec/helpers-spec.coffee spec/keymap-manager-spec.coffee

build: off
deploy: off
