version: "{build}"

platform: x86

clone_depth: 10

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run ci

deploy: off
